# Generated by Django 5.2.8 on 2025-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('DEGIRO', 'DeGiro'), ('IBKR', 'Interactive Brokers'), ('OTHER', 'Other')], default='IBKR', max_length=20)),
                ('symbol', models.CharField(max_length=50)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('trade_datetime', models.DateTimeField()),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
